---
- name: Converge cluster
  hosts: all
  vars:
    ansible_distro: "{{ ansible_distribution | lower | replace('\"', '') }}"
    mariadb_config_include_files:
      - src: "{{ playbook_dir }}/tools/99-useless.cnf"

  pre_tasks:
    #  https://www.jeffgeerling.com/blog/2020/resolving-fedora-dnf-error-no-such-file-or-directory-varlibdnfrpmdblockpid
    - name: Wait for systemd to complete initialization.  # noqa 303
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: >
        ansible_service_mgr == 'systemd' and
        ansible_distro in ("redhat", "centos", "fedora", "amazonlinux")
      changed_when: false
      ignore_errors: true  # because when the command returns degraded which is ok in this situation, the rc is still > 0
      tags: [always]

  roles:
    - role: claranet.mariadb
